"""Interactive viewer for inspecting extracted landmark samples.

This tool scans the ``landmarks`` directory populated by
``arabic_sign_landmarks.py`` and exposes a minimal Tkinter UI that lets you:

1. Pick a user, gesture, and repetition triple that exists in the
   ``landmarks/original`` CSV files.
2. Display the pose sequence for the selected sample alongside its flipped,
   slowed, and speed-up counterparts.
3. Scrub through frames with a slider and quickly jump back to the selection
   screen (arrow keys are also supported for stepping through frames).

The four variants are rendered on the same screen using Matplotlib together with
the original video loaded from the dataset directory, giving a side-by-side
overview of how the augmentations alter the trajectory of the captured joints.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence, Tuple

import cv2
import matplotlib

# TkAgg backend is required for embedding Matplotlib in Tkinter.
matplotlib.use("TkAgg")

import numpy as np
import pandas as pd
import tkinter as tk
from tkinter import messagebox, ttk
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure

# Repository-relative paths -------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_LANDMARK_ROOT = REPO_ROOT / "landmarks"

VARIANT_ORDER: Sequence[str] = ("original", "flipped", "slow_down", "speed_up")
METADATA_COLUMNS = (
    "user",
    "gesture",
    "repetition",
    "labels",
    "frame_count",
    "extraction_time_sec",
    "video_path",
)

GESTURE_LABEL_ITEMS: Sequence[Tuple[int, str]] = (
    (1, "Hi"),
    (2, "Please"),
    (3, "What?"),
    (4, "Arabic"),
    (5, "University"),
    (6, "You"),
    (7, "Eat"),
    (8, "Sleep"),
    (9, "Go"),
    (10, "UAE"),
)
GESTURE_LABELS: Mapping[int, str] = {idx: name for idx, name in GESTURE_LABEL_ITEMS}
GESTURE_LABEL_LEGEND = "\n".join(f"{idx:02d}. {name}" for idx, name in GESTURE_LABEL_ITEMS)

# Simple skeleton definition used when plotting the poses. The joints listed
# here match the column names generated by the extraction scripts.
BODY_CONNECTIONS: Sequence[tuple[str, str]] = (
    ("nose", "leftEye"),
    ("nose", "rightEye"),
    ("leftEye", "leftEar"),
    ("rightEye", "rightEar"),
    ("leftShoulder", "rightShoulder"),
    ("leftShoulder", "leftElbow"),
    ("leftElbow", "leftWrist"),
    ("rightShoulder", "rightElbow"),
    ("rightElbow", "rightWrist"),
)

HAND_CONNECTIONS: Sequence[tuple[str, str]] = (
    ("wrist", "thumbCMC"),
    ("thumbCMC", "thumbMP"),
    ("thumbMP", "thumbIP"),
    ("thumbIP", "thumbTip"),
    ("wrist", "indexMCP"),
    ("indexMCP", "indexPIP"),
    ("indexPIP", "indexDIP"),
    ("indexDIP", "indexTip"),
    ("wrist", "middleMCP"),
    ("middleMCP", "middlePIP"),
    ("middlePIP", "middleDIP"),
    ("middleDIP", "middleTip"),
    ("wrist", "ringMCP"),
    ("ringMCP", "ringPIP"),
    ("ringPIP", "ringDIP"),
    ("ringDIP", "ringTip"),
    ("wrist", "littleMCP"),
    ("littleMCP", "littlePIP"),
    ("littlePIP", "littleDIP"),
    ("littleDIP", "littleTip"),
)


def _parse_float_list(value: str) -> np.ndarray:
    """Return the numeric values embedded in the CSV cell.

    The extractor stores per-frame coordinates as JSON-encoded lists of floats.
    This helper converts each list into a NumPy array so we can efficiently
    slice frames.
    """

    if not isinstance(value, str):
        return np.asarray(value, dtype=np.float32)

    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        return np.zeros((0,), dtype=np.float32)

    return np.asarray(parsed, dtype=np.float32)


def _row_to_joint_sequences(row: pd.Series) -> Dict[str, np.ndarray]:
    """Transform a CSV row into {joint_name: np.ndarray[num_frames, 2]}."""

    grouped: Dict[str, Dict[str, np.ndarray]] = {}

    for column_name, cell in row.items():
        if column_name in METADATA_COLUMNS:
            continue

        if column_name.endswith("_X"):
            joint_name = column_name[:-2]
            grouped.setdefault(joint_name, {})["x"] = _parse_float_list(cell)
        elif column_name.endswith("_Y"):
            joint_name = column_name[:-2]
            grouped.setdefault(joint_name, {})["y"] = _parse_float_list(cell)

    result: Dict[str, np.ndarray] = {}
    for joint_name, coords in grouped.items():
        xs = coords.get("x")
        ys = coords.get("y")
        if xs is None or ys is None:
            continue

        frame_count = min(len(xs), len(ys))
        if frame_count == 0:
            continue

        stacked = np.stack([xs[:frame_count], ys[:frame_count]], axis=1)
        result[joint_name] = stacked

    return result


def _safe_int(value: object) -> Optional[int]:
    if isinstance(value, (int, np.integer)):
        return int(value)
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return None
        try:
            return int(stripped)
        except ValueError:
            return None
    return None


def _format_gesture_with_label(gesture_id: object, label_value: object) -> str:
    gesture_str = str(gesture_id) if gesture_id not in (None, "", "nan") else ""
    label_int = _safe_int(label_value)
    if label_int is None:
        return gesture_str or "Unknown"

    label_name = GESTURE_LABELS.get(label_int)
    label_text = f"{label_int:02d}"
    if label_name:
        label_text = f"{label_text} – {label_name}"

    if gesture_str:
        return f"{gesture_str} ({label_text})"
    return label_text


@dataclass
class SampleData:
    """Container for a single (user, gesture, repetition) sample."""

    variant: str
    metadata: Mapping[str, object]
    joints: Mapping[str, np.ndarray]

    @property
    def frame_count(self) -> int:
        frame_count = self.metadata.get("frame_count", 0)
        try:
            return int(frame_count)
        except (TypeError, ValueError):
            return 0


class LandmarkRepository:
    """Utility responsible for loading rows from the landmark CSVs."""

    def __init__(self, landmark_root: Path):
        self.landmark_root = landmark_root
        self._cache: Dict[tuple[str, str], pd.DataFrame] = {}
        self._index = self._build_index()

    def _build_index(self) -> Dict[str, Dict[str, List[str]]]:
        """Scan original CSVs and record available gestures/repetitions."""

        index: Dict[str, Dict[str, List[str]]] = {}
        original_dir = self.landmark_root / "original"
        csv_paths = sorted(original_dir.glob("*.csv"))
        for csv_path in csv_paths:
            user_id = csv_path.stem
            try:
                df = pd.read_csv(csv_path, usecols=["gesture", "repetition"])
            except FileNotFoundError:
                continue

            gesture_map: MutableMapping[str, set[str]] = {}
            for _, row in df.iterrows():
                gesture = str(row["gesture"])
                repetition = str(row["repetition"])
                gesture_map.setdefault(gesture, set()).add(repetition)

            index[user_id] = {
                gesture: sorted(repetitions)
                for gesture, repetitions in sorted(gesture_map.items())
            }

        return index

    def users(self) -> Sequence[str]:
        return sorted(self._index.keys())

    def gestures_for_user(self, user: str) -> Sequence[str]:
        return sorted(self._index.get(user, {}).keys())

    def repetitions_for(self, user: str, gesture: str) -> Sequence[str]:
        gestures = self._index.get(user, {})
        return gestures.get(gesture, [])

    def _load_dataframe(self, variant: str, user: str) -> pd.DataFrame:
        cache_key = (variant, user)
        if cache_key not in self._cache:
            csv_path = self.landmark_root / variant / f"{user}.csv"
            self._cache[cache_key] = pd.read_csv(csv_path)
        return self._cache[cache_key]

    def load_sample(
        self, variant: str, user: str, gesture: str, repetition: str
    ) -> SampleData:
        df = self._load_dataframe(variant, user)
        mask = (
            (df["gesture"].astype(str) == gesture)
            & (df["repetition"].astype(str) == repetition)
        )
        subset = df[mask]
        if subset.empty:
            raise ValueError(
                f"No row found for {user} {gesture} {repetition} in {variant}"
            )

        row = subset.iloc[0]
        metadata = {column: row[column] for column in METADATA_COLUMNS}
        metadata["frame_count"] = int(metadata["frame_count"])
        joints = _row_to_joint_sequences(row)
        return SampleData(variant=variant, metadata=metadata, joints=joints)

    def load_all_variants(
        self, user: str, gesture: str, repetition: str
    ) -> List[SampleData]:
        samples: List[SampleData] = []
        for variant in VARIANT_ORDER:
            samples.append(self.load_sample(variant, user, gesture, repetition))
        return samples


class SampleSelectionFrame(ttk.Frame):
    """User/Gesture/Repetition selection UI."""

    def __init__(
        self,
        master: tk.Misc,
        repository: LandmarkRepository,
        on_sample_selected,
    ) -> None:
        super().__init__(master)
        self.repository = repository
        self.on_sample_selected = on_sample_selected

        self.user_var = tk.StringVar()
        self.gesture_var = tk.StringVar()
        self.rep_var = tk.StringVar()

        ttk.Label(self, text="Select a sample to visualize", font=("Segoe UI", 14)).pack(
            pady=20
        )

        self.user_combo = self._create_combobox(
            "User", self.user_var, self._handle_user_change
        )
        self.gesture_combo = self._create_combobox(
            "Gesture", self.gesture_var, self._handle_gesture_change
        )
        self.rep_combo = self._create_combobox(
            "Repetition", self.rep_var, self._update_button_state
        )

        legend_frame = ttk.Frame(self)
        legend_frame.pack(pady=10)
        ttk.Label(legend_frame, text="Gesture Labels:", font=("Segoe UI", 11, "bold")).pack(
            anchor=tk.W
        )
        ttk.Label(
            legend_frame,
            text=GESTURE_LABEL_LEGEND,
            justify=tk.LEFT,
            font=("Segoe UI", 10),
        ).pack(anchor=tk.W)

        self.load_button = ttk.Button(
            self,
            text="Load Sample",
            command=self._emit_selection,
            state=tk.DISABLED,
        )
        self.load_button.pack(pady=30)

        users = repository.users()
        self.user_combo["values"] = users
        if users:
            self.user_combo.current(0)
            self._handle_user_change()

    def _create_combobox(
        self, label_text: str, variable: tk.StringVar, callback
    ) -> ttk.Combobox:
        frame = ttk.Frame(self)
        frame.pack(pady=8)
        ttk.Label(frame, text=label_text + ":").pack(side=tk.LEFT, padx=5)
        combo = ttk.Combobox(
            frame,
            textvariable=variable,
            state="readonly",
            width=20,
        )
        combo.pack(side=tk.LEFT, padx=5)
        combo.bind("<<ComboboxSelected>>", lambda *_: callback())
        return combo

    def _handle_user_change(self) -> None:
        user = self.user_var.get()
        gestures = self.repository.gestures_for_user(user)
        self.gesture_combo["values"] = gestures
        if gestures:
            self.gesture_combo.current(0)
        else:
            self.gesture_combo.set("")
        self._handle_gesture_change()

    def _handle_gesture_change(self) -> None:
        user = self.user_var.get()
        gesture = self.gesture_var.get()
        repetitions = self.repository.repetitions_for(user, gesture)
        self.rep_combo["values"] = repetitions
        if repetitions:
            self.rep_combo.current(0)
        else:
            self.rep_combo.set("")
        self._update_button_state()

    def _update_button_state(self) -> None:
        state = (
            tk.NORMAL
            if self.user_var.get() and self.gesture_var.get() and self.rep_var.get()
            else tk.DISABLED
        )
        self.load_button.config(state=state)

    def _emit_selection(self) -> None:
        self.on_sample_selected(
            self.user_var.get(), self.gesture_var.get(), self.rep_var.get()
        )


class SampleDisplayFrame(ttk.Frame):
    """Pose visualization screen."""

    def __init__(
        self,
        master: tk.Misc,
        on_back,
        dataset_root: Optional[Path],
        **kwargs,
    ) -> None:
        super().__init__(master, **kwargs)
        self.on_back = on_back
        self.dataset_root = dataset_root
        self.samples: Dict[str, SampleData] = {}
        self.frame_index = 0
        self.video_frames: List[np.ndarray] = []
        self.video_path: Optional[Path] = None
        self.video_missing_reason: Optional[str] = None
        self.video_height: int = 0
        self.video_width: int = 0

        top_bar = ttk.Frame(self)
        top_bar.pack(fill=tk.X, pady=10)

        self.info_label = ttk.Label(top_bar, text="", font=("Segoe UI", 12))
        self.info_label.pack(side=tk.LEFT, padx=10)

        ttk.Button(top_bar, text="Back", command=self._handle_back).pack(
            side=tk.RIGHT, padx=10
        )

        self.figure = Figure(figsize=(10, 7), dpi=100)
        grid = self.figure.add_gridspec(3, 2, height_ratios=[1.2, 1, 1], hspace=0.35)
        self.video_ax = self.figure.add_subplot(grid[0, :])
        self.axes = [
            self.figure.add_subplot(grid[row, col])
            for row in (1, 2)
            for col in (0, 1)
        ]
        for ax in self.axes:
            ax.set_xticks([])
            ax.set_yticks([])

        self.canvas = FigureCanvasTkAgg(self.figure, master=self)
        self.canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True)

        slider_frame = ttk.Frame(self)
        slider_frame.pack(fill=tk.X, pady=10)
        ttk.Label(slider_frame, text="Frame:").pack(side=tk.LEFT, padx=8)

        self.frame_slider = ttk.Scale(
            slider_frame,
            from_=0,
            to=0,
            orient=tk.HORIZONTAL,
            command=self._handle_slider,
        )
        self.frame_slider.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=8)

        self.frame_value_label = ttk.Label(slider_frame, text="0")
        self.frame_value_label.pack(side=tk.LEFT, padx=8)

        self.bind_all("<Left>", self._handle_left_key)
        self.bind_all("<Right>", self._handle_right_key)

    def _handle_back(self) -> None:
        self.on_back()

    def _handle_slider(self, value: str) -> None:
        try:
            self.frame_index = int(float(value))
        except ValueError:
            self.frame_index = 0
        self.frame_value_label.config(text=str(self.frame_index))
        self._redraw()

    def show_samples(self, samples: Iterable[SampleData]) -> None:
        self.samples = {sample.variant: sample for sample in samples}
        self._load_video_frames()
        if self.video_frames:
            max_frames = len(self.video_frames)
        else:
            counts: List[int] = [sample.frame_count for sample in self.samples.values()]
            max_frames = max(counts) if counts else 0
        self.frame_index = 0
        self.frame_slider.configure(from_=0, to=max(0, max_frames - 1))
        self.frame_slider.set(0)
        self.frame_value_label.config(text="0")
        self._refresh_info_label()
        self._redraw()

    def _refresh_info_label(self) -> None:
        if "original" not in self.samples:
            self.info_label.config(text="No sample loaded.")
            return

        sample = self.samples["original"]
        meta = sample.metadata
        gesture_text = _format_gesture_with_label(meta.get("gesture"), meta.get("labels"))
        counts_text = ", ".join(
            f"{variant}: {self.samples[variant].frame_count}"
            for variant in VARIANT_ORDER
            if variant in self.samples
        )
        text = (
            f"User: {meta.get('user')} | Gesture: {gesture_text} | "
            f"Repetition: {meta.get('repetition')} | Frames -> {counts_text}"
        )
        self.info_label.config(text=text)

    def _redraw(self) -> None:
        self._draw_video()
        for axis, variant in zip(self.axes, VARIANT_ORDER):
            axis.clear()
            axis.set_xticks([])
            axis.set_yticks([])
            axis.set_xlim(0, 1)
            axis.set_ylim(1, 0)
            axis.set_title(variant.replace("_", " ").title())

            sample = self.samples.get(variant)
            if not sample:
                axis.text(0.5, 0.5, "Missing", ha="center", va="center")
                continue

            frame_idx = min(self.frame_index, max(0, sample.frame_count - 1))
            self._plot_sample_on_axis(axis, sample, frame_idx)

        self.canvas.draw_idle()

    def _draw_video(self) -> None:
        self.video_ax.clear()
        self.video_ax.set_xticks([])
        self.video_ax.set_yticks([])

        if self.video_frames:
            idx = self._video_frame_for_index(self.frame_index)
            frame = self.video_frames[idx]
            name = self.video_path.name if self.video_path else "video"
            self.video_ax.imshow(frame)
            sample = self.samples.get("original")
            gesture_desc = None
            if sample:
                frame_idx = min(idx, max(0, sample.frame_count - 1))
                points = self._collect_points(sample, frame_idx)
                if points:
                    self._draw_pose_overlay(points)
                gesture_desc = _format_gesture_with_label(
                    sample.metadata.get("gesture"), sample.metadata.get("labels")
                )
            title_parts = [
                f"Original Video ({name})",
                gesture_desc or "Unknown gesture",
                f"frame {idx + 1}/{len(self.video_frames)}",
            ]
            self.video_ax.set_title(" | ".join(title_parts))
        else:
            message = self.video_missing_reason or "Video unavailable"
            self.video_ax.text(0.5, 0.5, message, ha="center", va="center")
            self.video_ax.set_title("Original Video")

    def _plot_sample_on_axis(
        self, axis, sample: SampleData, frame_idx: int
    ) -> None:
        points = self._collect_points(sample, frame_idx)

        if not points:
            axis.text(0.5, 0.5, "No visible joints", ha="center", va="center")
            return

        def draw_connection(a: str, b: str, **kwargs) -> None:
            pa = points.get(a)
            pb = points.get(b)
            if pa and pb:
                axis.plot(
                    [pa[0], pb[0]],
                    [pa[1], pb[1]],
                    **kwargs,
                )

        for start, end in BODY_CONNECTIONS:
            draw_connection(start, end, color="#2081C3", linewidth=2)

        for suffix in ("0", "1"):
            for start, end in HAND_CONNECTIONS:
                draw_connection(
                    f"{start}_{suffix}",
                    f"{end}_{suffix}",
                    color="#ED6A5E",
                    linewidth=1.5,
                )

        xs = [coord[0] for coord in points.values()]
        ys = [coord[1] for coord in points.values()]
        axis.scatter(xs, ys, s=20, color="#222222")

    def _handle_left_key(self, event) -> None:  # noqa: ANN001 - Tkinter callback signature.
        if not self.samples and not self.video_frames:
            return
        self._adjust_frame(-1)

    def _handle_right_key(self, event) -> None:  # noqa: ANN001 - Tkinter callback signature.
        if not self.samples and not self.video_frames:
            return
        self._adjust_frame(1)

    def _adjust_frame(self, delta: int) -> None:
        slider_min = int(float(self.frame_slider["from"]))
        slider_max = int(float(self.frame_slider["to"]))
        if slider_max < slider_min:
            return
        new_value = int(np.clip(self.frame_index + delta, slider_min, slider_max))
        self.frame_slider.set(new_value)

    def _load_video_frames(self) -> None:
        self.video_frames = []
        self.video_path = None
        self.video_missing_reason = None
        self.video_height = 0
        self.video_width = 0

        if not self.dataset_root:
            self.video_missing_reason = "Dataset root not provided"
            return

        sample = self.samples.get("original")
        if not sample:
            self.video_missing_reason = "Original variant missing"
            return

        video_rel = sample.metadata.get("video_path")
        if not isinstance(video_rel, str):
            self.video_missing_reason = "Video path missing from metadata"
            return

        video_path = (self.dataset_root / video_rel).resolve()
        if not video_path.exists():
            self.video_missing_reason = f"Video not found: {video_path}"
            return

        cap = cv2.VideoCapture(str(video_path))
        if not cap.isOpened():
            self.video_missing_reason = f"Failed to open video: {video_path}"
            return

        try:
            while True:
                ret, frame = cap.read()
                if not ret:
                    break
                if not self.video_frames:
                    self.video_height, self.video_width = frame.shape[:2]
                rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                self.video_frames.append(rgb)
        finally:
            cap.release()

        if not self.video_frames:
            self.video_missing_reason = "Video contains no frames"
        else:
            self.video_path = video_path

    def _video_frame_for_index(self, frame_idx: int) -> int:
        if not self.video_frames:
            return 0
        return min(frame_idx, len(self.video_frames) - 1)

    def _collect_points(
        self, sample: SampleData, frame_idx: int
    ) -> Dict[str, tuple[float, float]]:
        points: Dict[str, tuple[float, float]] = {}
        for joint_name, coords in sample.joints.items():
            if frame_idx >= len(coords):
                continue
            x, y = coords[frame_idx]
            if x == 0 and y == 0:
                continue
            points[joint_name] = (float(x), float(y))
        return points

    def _draw_pose_overlay(self, points: Mapping[str, tuple[float, float]]) -> None:
        if not self.video_height or not self.video_width:
            return

        def scaled(point_name: str) -> Optional[tuple[float, float]]:
            pt = points.get(point_name)
            if not pt:
                return None
            x = float(pt[0]) * (self.video_width - 1)
            y = float(pt[1]) * (self.video_height - 1)
            return x, y

        def draw_connection(a: str, b: str, **kwargs) -> None:
            pa = scaled(a)
            pb = scaled(b)
            if pa and pb:
                self.video_ax.plot([pa[0], pb[0]], [pa[1], pb[1]], **kwargs)

        for start, end in BODY_CONNECTIONS:
            draw_connection(start, end, color="#2081C3", linewidth=2)

        for suffix in ("0", "1"):
            for start, end in HAND_CONNECTIONS:
                draw_connection(
                    f"{start}_{suffix}",
                    f"{end}_{suffix}",
                    color="#ED6A5E",
                    linewidth=1.5,
                )

        xs: List[float] = []
        ys: List[float] = []
        for joint_name, pt in points.items():
            scaled_pt = scaled(joint_name)
            if scaled_pt:
                xs.append(scaled_pt[0])
                ys.append(scaled_pt[1])
        if xs and ys:
            self.video_ax.scatter(xs, ys, s=15, color="#111111")


class LandmarkViewerApp(tk.Tk):
    """Top-level Tkinter application."""

    def __init__(
        self, repository: LandmarkRepository, dataset_root: Optional[Path]
    ) -> None:
        super().__init__()
        self.repository = repository
        self.title("SPOTER Landmark Viewer")
        self.geometry("1200x900")

        self.selection_frame = SampleSelectionFrame(
            self, repository, self._handle_sample_request
        )
        self.display_frame = SampleDisplayFrame(
            self,
            on_back=self._show_selection_frame,
            dataset_root=dataset_root,
        )

        self.selection_frame.pack(fill=tk.BOTH, expand=True)

    def _show_selection_frame(self) -> None:
        self.display_frame.pack_forget()
        self.selection_frame.pack(fill=tk.BOTH, expand=True)

    def _show_display_frame(self) -> None:
        self.selection_frame.pack_forget()
        self.display_frame.pack(fill=tk.BOTH, expand=True)

    def _handle_sample_request(self, user: str, gesture: str, repetition: str) -> None:
        try:
            samples = self.repository.load_all_variants(user, gesture, repetition)
        except Exception as exc:  # noqa: BLE001 - surface all issues to the user.
            messagebox.showerror("Failed to load sample", str(exc))
            return

        self.display_frame.show_samples(samples)
        self._show_display_frame()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Visualize extracted landmark sequences with their augmented "
            "variants side by side."
        )
    )
    parser.add_argument(
        "--landmark-root",
        type=Path,
        default=DEFAULT_LANDMARK_ROOT,
        help="Directory that contains the original/flipped/speed variants.",
    )
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=REPO_ROOT / "dataset",
        help="Directory that stores the raw dataset videos referenced by video_path.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.landmark_root.exists():
        raise SystemExit(f"Landmark directory not found: {args.landmark_root}")

    repository = LandmarkRepository(args.landmark_root)
    if not repository.users():
        raise SystemExit(f"No landmark CSV files found under {args.landmark_root}")

    dataset_root = args.dataset_root.resolve()
    if not dataset_root.exists():
        dataset_root = None

    app = LandmarkViewerApp(repository, dataset_root=dataset_root)
    app.mainloop()


if __name__ == "__main__":
    main()
